#!/usr/bin/env python3
"""Generate figures.tex from main.tex's Figure Legends section.

    venv/bin/python paper/tex/rsna/make_figures_tex.py

The journal requires the combined figure document's legends to match the
manuscript's. Typing them twice guarantees they drift, so this extracts them from
main.tex and writes figures.tex. Edit legends in main.tex only.

It also enforces the placement rule. The instruction is that legends follow their
figure immediately, so each image is placed with \\begin{center} and never inside
a float: a float lets LaTeX carry the image to a page of its own, away from its
legend. An earlier revision used [p] on one figure and did exactly that.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAIN = HERE / "main.tex"
OUT = HERE / "figures.tex"

FIGFILES = {
    1: "fig1_collapse.pdf",
    2: "fig2_unit_scatter.pdf",
    3: "fig3_bin_agg_grid.pdf",
}

PREAMBLE = r"""% =====================================================================
%  FIGURE DOCUMENT -- submitted as its own file, separate from main.tex.
%
%  GENERATED by make_figures_tex.py from main.tex. Do not edit legends
%  here; edit main.tex and regenerate.
%
%  The journal's instruction, verbatim: "For new submissions, figures
%  should be combined into one text document in the order they appear in
%  the text, with figure legends immediately following the relevant
%  figure." Each figure is therefore placed with \begin{center}, NOT
%  inside a float, which would let LaTeX separate image from legend.
%
%  All three figures are anonymous: no institution, no repository, no
%  filenames that identify the authors. The descriptive cross-study
%  comparison is not a main-text figure; it is Figure S1 in supplement.tex.
%
%  Build: tectonic figures.tex
% =====================================================================
\documentclass[11pt,letterpaper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{mathptmx}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{siunitx}

\sisetup{group-separator={,},group-minimum-digits=4}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.6em}

\begin{document}

"""


def main() -> None:
    src = MAIN.read_text()
    sec = src[src.index(r"\section*{Figure Legends}"):src.index("%  TABLES")]
    legends: dict[int, str] = {}
    for part in re.split(r"(?=\\textbf\{Figure \d+\.\})", sec):
        m = re.match(r"\\textbf\{Figure (\d+)\.\}", part.strip())
        if m:
            legends[int(m.group(1))] = part.strip().rstrip("%").strip()

    missing = set(FIGFILES) - set(legends)
    extra = set(legends) - set(FIGFILES)
    if missing or extra:
        sys.exit(f"legend/figure mismatch: missing {sorted(missing)}, "
                 f"unexpected {sorted(extra)}")
    for i, name in FIGFILES.items():
        if not (HERE / "figures" / name).exists():
            sys.exit(f"missing figure file for Figure {i}: figures/{name}")

    body = [
        "\\begin{center}\n\\includegraphics[width=\\textwidth]{figures/%s}\n"
        "\\end{center}\n\n%s\n" % (FIGFILES[i], legends[i])
        for i in sorted(FIGFILES)
    ]
    out = PREAMBLE + "\n\\clearpage\n\n".join(body) + "\n\\end{document}\n"
    if r"\begin{figure}" in out:
        sys.exit("refusing to write: a float reached the figure document")
    OUT.write_text(out)
    print(f"wrote {OUT.name}: {len(FIGFILES)} figures, legends taken from main.tex")


if __name__ == "__main__":
    main()
